### ISSUE TITLE
Sep 21, 2022 Weekly Meeting

### ISSUE THREAD

**Issue by zekun-li** [machines-reading-maps/mapkurator-system#11]
1. linking + postocr module 
2. clustering and fine-tuning for specific map types
3. multilingual -> tesseract

**Comment by Jina-Kim** [comment]
Post-OCR + Entity Linker
- [x] Install elasticsearch and logstash under maploard account @MinNamgung 
- [X] Create one table to store all OSM features over entire world (87,318,480 in total) @Jina-Kim 

  **table name: `all_continents` under `mrm` account (excluding features with no name)** 
  - africa - 2,692,063
  - antarctica - 3,982
  - asia - 14,642,503
  - australia_oceania - 2,014,401
  - central_america - 937,076
  - europe - 40,354,736
  - north_america - 20,713,086
  - south_america - 5,960,633

- [x] Connect postgres to elasticsearch to upload entire OpenStreetMap feature @Jina-Kim 
- [ ] Error analysis - why aren't all 87,318,480 features are uploaded? 
- [ ] Update popularity score, OpenStreetMap ID, corresponding map image ID to elasticsearch @MinNamgung 
- [ ] Update Post-OCR module @MinNamgung 
- [ ] Integrate Entity Linker module into Post-OCR @Jina-Kim 

Output file: GeoJSON in geocoordinates (store Post-OCR output, EntityLinker output, image coordinates)
