### ISSUE TITLE
July 14, 2022 Weekly Meeting

### ISSUE THREAD

**Issue by zekun-li** [machines-reading-maps/mapkurator-system#3]
- [x] (1 week) Handle ground control points with Polynomial and TPS transform @Jina-Kim 
- [x] (1 week) Improve text spotter with synthetic maps @linyijun @MinNamgung 
- [ ] (2 weeks) Handle text labels spanning across multiple tiles @zekun-li 
- [x] Upgrade spotting to TESTER @MinNamgung @linyijun @zekun-li 
- [ ] 100 samples from Turing @all 
- [x] Start running 57K @all 
- [x] ~~GeoTiff generation for all files~~ @zekun-li 
- [x] Time usage for Image-to-Geo coord converter @Jina-Kim

**Comment by Jina-Kim** [comment]
- [x] Create and share the new account @zekun-li 
- [x] Configure conda environment for TESTR @MinNamgung 
- [x] Add libraries for entity linking (after TESTR configuration) @Jina-Kim 

Running 100 maps from Turing @ALL (https://drive.google.com/drive/folders/1fA9RXc219i_cdPK1mU2bYyr_KS_F077s)
  (/home/maplord/maplist_csv/Turing_100_Maps.csv)
Running 56,628 maps @ALL
- [x] Run SID to JPG conversion @zekun-li
(log: /data2/rumsey_output/57k_maps/error_reason_2022_07_26-07:38:05_PM.csv)

- [x] Add image name column to LUNA & OMO joint metadata @zekun-li (/home/maplord/maplist_csv/luna_omo_metadata_56628_20220724.csv, also on [google drive](https://drive.google.com/drive/folders/1Nby1JaIzNSwrGtGFn5Af0VL5y3TGLZGQ)) 

- [x] Run image cropping for all @zekun-li
(log: /data2/rumsey_output/57k_maps/error_reason_2022_07_31-09:56:50_PM.csv)

- [x] Prepare the model for inferencing @linyijun 
- [ ] Run model 2 @linyijun 
- [ ] Run model 3 @zekun-li
- [ ] Run Post-OCR @MinNamgung 
- [ ] Run module 4. geocoord converter @Jina-Kim 

Entity Linking (2~3 weeks)
- [x] Update post-ocr module (approach w/ best performance) @MinNamgung 
- [ ] Update entity linker after Min's post-ocr module @Jina-Kim

**Comment by zekun-li** [comment]
- [ ] error log: external_id, image path and error reason

**Comment by Jina-Kim** [comment]
Annotations on Minnesota map w/ new guidelines
- [x] top-left @Jina-Kim 
- [x] top-right @MinNamgung 
- [x] bottom-left @zekun-li 
- [x] bottom-right @linyijun

**Comment by zekun-li** [comment]
- [x] Move all originally downloaded image files (from old maps online and Luna) to MSI S3 @Jina-Kim
> - moved to s3 bucket 
> /data/rumsey-jp2 /data/rumsey-sid /data2/rumsey_sid_jpg /data2/rumsey-luna-img
> - deleted in sansa 
> /data/rumsey-sid  /data2/rumsey_jp2.tar
- [x] Make a copy of all jpg/jp2 files for all map images and store the copies to MSI S3 @Jina-Kim 
- [x] Make sure Sansa only contains the jpg/jp2 files for all map images but not duplicates (e.g., do not have both SID and jpg formats of the same map are on Sansa) @Jina-Kim
