### ISSUE TITLE
gazetteer selection for geocoding

### ISSUE THREAD

**Issue by kmcdono2** [machines-reading-maps/mapkurator-system#5]
@zekun-li and @Jina-Kim - sharing some thoughts here about next steps with the geocoding part of processing un-geo-referenced maps.

The geocoder that you used is great as a first step. He has made it easy to access many of the basic gazetteer resources that work well for toponym-level place data in the contemporary (e.g. 21st c.) developed world. At some point, it will be best to have a way to use a selected gazetteer that is unlikely to be one of the resources available in https://github.com/DenisCarriere/geocoder.

For reference, the 3 resources you have selected (ArcGIS, Google, Geonames) are largely based (for US data) on the GNIS gazetteer, available here as a dataset: https://www.usgs.gov/u.s.-board-on-geographic-names/download-gnis-data. The GNIS gazetteer is the base gazetteer used by, for example, USGS on their topo maps. ArcGIS, Google, and especially Geonames supplement this data a little, but the vast majority is from GNIS. The results are not going to differ too much between the resources because they essentially have the same underlying data. When they do differ in ArcGIS and Google, it is a big problem that we don't necessarily know the resource providing the data. The provenance of this data is crucial to understanding the quality of the results.

Additionally (and importantly), GNIS does not include street names. Street name data for the US is available mostly from the census, e.g. https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2021&layergroup=Roads, but this is polyline vector data, not just point data, so label placement is an issue. This means the street data that you are finding comes from a non-GNIS resource, but it's not clear what that is.

With this in mind, I have a two suggestions right now. 

- First, I think it would be good to create a kind of "decision tree" to help you decide which gazetteer is best for geocoding a particular set of maps. I am happy to work on this with you. Many times we need to think carefully about the geographical coverage of the maps and their date of publication in order to select the best gazetteer. For the Sanborn maps, a gazetteer with strong street-level data and even names of buildings/landmarks would be best: this would probably be a mix of OSM and Wikidata, not geonames. For the smaller-scale maps, geonames/GNIS is fine because those will largely contain names of populated places or other major administrative toponyms.

- Second, in the short term, I think it would be best to show the results from Geonames rather than ArcGIS or Google given the issues with the closed nature of their gazetteers.

**Comment by zekun-li** [comment]
Thanks for the detailed comments. I'll discuss with Yao-Yi upon this. 

Currently we are using existing geo-coders to find the locations instead of string comparison of gazeteers. My concern about using gazeteers directly is that it would require a totally different system for parsing and matching the place names, which takes quite some time and effort to build.
